### ISSUE TITLE
phenotype table

### ISSUE THREAD

**Issue by sehee59** [chengzhouwu/gbdmr#2]
I have a question. 
In the phenotype table in the gbdmr tutorial, you seem to have DMR and DMP detection for two phenotypes with age and sex, but how can there be one DMR_summarylist for these two phenotypes? If there are two phenotypes, shouldn't there be at least two for each phenotype?

**Comment by chengzhouwu** [comment]
Thank you for reaching out. 

For your phenotype of interest, we report only one p-value because we used the log-likelihood ratio test. Other variables in the model serve as confounders, which we adjust for based on your requirements. 

When using the program, please ensure that:
X: The covariates are in an 𝑛×𝑝 matrix, where 𝑛 is the sample size and 𝑝 is the number of covariates. The first column should be your interested phenotype.


**For example, if age and sex are the two variables:**

When age is in the first column, we report p-values for age-related DMRs and DMPs, adjusting for sex as a confounder.

Similarly, if sex is in the first column, we report p-values for sex-related DMRs and DMPs, with age as the confounder.

**Comment by sehee59** [comment]
Thank you for your response.
